import type { LocalModelDefinition } from './localSttTypes.js';

const WHISPER_CPP_MODELS = 'https://huggingface.co/ggerganov/whisper.cpp/tree/main';

export const LOCAL_MODEL_REGISTRY: readonly LocalModelDefinition[] = [
  {
    id: 'whisper-base-q5_1',
    provider: 'local-whisper',
    displayName: 'Whisper base multilingual Q5_1',
    fileName: 'ggml-base-q5_1.bin',
    sourceUrl: WHISPER_CPP_MODELS,
    downloadSizeLabel: '59.7 MB',
    downloadSizeBytes: 59_700_000,
    estimatedRamMiB: 388,
    license: 'MIT (distribution repository metadata)',
    quantization: 'Q5_1',
    languages: ['ja', 'en'],
    whisperCppCompatible: true,
    openVinoEncoderCompatible: false,
  },
  {
    id: 'whisper-small-q5_1',
    provider: 'local-whisper',
    displayName: 'Whisper small multilingual Q5_1',
    fileName: 'ggml-small-q5_1.bin',
    sourceUrl: WHISPER_CPP_MODELS,
    downloadSizeLabel: '190 MB',
    downloadSizeBytes: 190_000_000,
    estimatedRamMiB: 852,
    license: 'MIT (distribution repository metadata)',
    quantization: 'Q5_1',
    languages: ['ja', 'en'],
    whisperCppCompatible: true,
    openVinoEncoderCompatible: false,
  },
  {
    id: 'whisper-base-en-q5_1',
    provider: 'local-whisper',
    displayName: 'Whisper base.en Q5_1',
    fileName: 'ggml-base.en-q5_1.bin',
    sourceUrl: WHISPER_CPP_MODELS,
    downloadSizeLabel: '59.7 MB',
    downloadSizeBytes: 59_700_000,
    estimatedRamMiB: 388,
    license: 'MIT (distribution repository metadata)',
    quantization: 'Q5_1',
    languages: ['en'],
    whisperCppCompatible: true,
    openVinoEncoderCompatible: false,
  },
  {
    id: 'whisper-small-en-q5_1',
    provider: 'local-whisper',
    displayName: 'Whisper small.en Q5_1',
    fileName: 'ggml-small.en-q5_1.bin',
    sourceUrl: WHISPER_CPP_MODELS,
    downloadSizeLabel: '190 MB',
    downloadSizeBytes: 190_000_000,
    estimatedRamMiB: 852,
    license: 'MIT (distribution repository metadata)',
    quantization: 'Q5_1',
    languages: ['en'],
    whisperCppCompatible: true,
    openVinoEncoderCompatible: false,
  },
  {
    id: 'kotoba-whisper-v2-q5_0',
    provider: 'local-kotoba',
    displayName: 'Kotoba-Whisper v2.0 GGML Q5_0',
    fileName: 'ggml-kotoba-whisper-v2.0-q5_0.bin',
    sourceUrl: 'https://huggingface.co/kotoba-tech/kotoba-whisper-v2.0-ggml/tree/main',
    downloadSizeLabel: '538 MB',
    downloadSizeBytes: 538_000_000,
    license: 'Apache-2.0',
    quantization: 'Q5_0',
    languages: ['ja'],
    whisperCppCompatible: true,
    openVinoEncoderCompatible: false,
  },
];

export function getLocalModelDefinition(modelId: string): LocalModelDefinition | undefined {
  return LOCAL_MODEL_REGISTRY.find((model) => model.id === modelId);
}
